services:

##########################################
##
## the-garudaworks-dashboard / bootstrap front end
##
##########################################

    the-garudaworks-dashboard-web:

        container_name: the-garudaworks-dashboard-web

        image: softwareshinobi/the-garudaworks-dashboard-web:intranet

        build: 

            context: web

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "10.28.1.1:8080:80"

##########################################
##
## the-garudaworks-dashboard / spring rest back end
##
##########################################

    the-garudaworks-dashboard-api:
cker
        container_name: the-garudaworks-dashboard-api
        
        image: softwareshinobi/the-garudaworks-dashboard-api:intranet

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "10.28.1.1:8888:8888"

        environment:

            DB_HOST: 10.28.1.1

            DB_NAME: kanban_flow_api

            DB_USER: kanban_flow_api

            DB_PASS: kanban_flow_api

##########################################
##
## the-garudaworks-dashboard / documentation
##
##########################################

    the-garudaworks-dashboard-docs:

        container_name: the-garudaworks-dashboard-docs

        image: softwareshinobi/the-garudaworks-dashboard-docs:intranet

        build: 

            context: docs

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "10.28.1.1:8081:80"
