services:

##########################################
##
## kanbanflow / data management
##
##########################################

    kanbanflow-database:

        container_name: kanbanflow-database

        image: mariadb:latest

        ports:

            - "3306:3306"
      
        restart: unless-stopped

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride
            
            MYSQL_DATABASE: kanbanflow

            MYSQL_USER: kanbanflow

            MYSQL_PASSWORD: kanbanflow

    kanbanflow-phpmyadmin:

        container_name: kanbanflow-phpmyadmin

        image: beeyev/phpmyadmin-lightweight:latest

        restart: unless-stopped

        ports:

            - "3380:80"
      
        depends_on:
        
            - kanbanflow-database

        environment:
    
            PMA_HOST: kanbanflow-database

            PMA_PORT: 3306

            PMA_ARBITRARY: 1

    kanbanflow-apis:
      
        container_name: kanbanflow-apis
        
        image: softwareshinobi/kanbanflow-apis:main

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - 8888:8888
        
        environment:

            DB_HOST: kanbanflow-database
            
            DB_PORT: 3306

            DB_NAME: kanbanflow

            DB_USER: kanbanflow

            DB_PASS: kanbanflow

    kanbanflow-app:

        container_name: kanbanflow-app

        image: softwareshinobi/kanbanflow-app:main

        build: 

            context: app

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - 8000:80

        environment:

            - API_URL=http://localhost:8888

            #- API_URL=https://apis.identity.ariaos.online

    kanbanflow-docs:

        container_name: kanbanflow-docs

        image: softwareshinobi/kanbanflow-docs:main

        build: 

            context: docs

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - 8880:80
