services:

##########################################
##
## kanban-flow-dashboard / data management
##
##########################################

    kanban-flow-dashboard-database:

        container_name: kanban-flow-dashboard-database

        image: mariadb:latest

        ports:

            - "3306:3306"
      
        restart: unless-stopped

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride
            
            MYSQL_DATABASE: sandbox

            MYSQL_USER: sandbox

            MYSQL_PASSWORD: sandbox

    kanban-flow-dashboard-phpmyadmin:

        container_name: kanban-flow-dashboard-phpmyadmin

        image: beeyev/phpmyadmin-lightweight:latest

        restart: unless-stopped

        ports:

            - "3380:80"
      
        depends_on:
        
            - kanban-flow-dashboard-database

        environment:
    
            PMA_HOST: kanban-flow-dashboard-database

            PMA_PORT: 3306

            PMA_ARBITRARY: 1

    kanban-flow-dashboard-apis:
      
        container_name: kanban-flow-dashboard-apis
        
        image: softwareshinobi/kanban-flow-dashboard-apis

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"
        
        environment:

            DB_HOST: kanban-flow-dashboard-database
            
            DB_PORT: 3306

            DB_NAME: sandbox

            DB_USER: sandbox

            DB_PASS: sandbox

    kanban-flow-dashboard-web-adminlte:

        container_name: kanban-flow-dashboard-web-adminlte

        image: softwareshinobi/kanban-flow-dashboard-web:adminlte

        build: 

            context: web/adminlte

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8000:80"

    kanban-flow-dashboard-web-admincast:

        container_name: kanban-flow-dashboard-web-admincast

        image: softwareshinobi/kanban-flow-dashboard-web:admincast

        build: 

            context: web/admincast

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8001:80"

    kanban-flow-dashboard-web-darkpan:

        container_name: kanban-flow-dashboard-web-darkpan

        image: softwareshinobi/kanban-flow-dashboard-web:darkpan

        build: 

            context: web/darkpan

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8002:80"

    kanban-flow-dashboard-docs:

        container_name: kanban-flow-dashboard-docs

        image: softwareshinobi/kanban-flow-dashboard:docs

        build: 

            context: docs

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8880:80"
