services:

    KanbanFlow-app-standalone:

        container_name: KanbanFlow-app-standalone

        image: embanet/kanbanflow-app:main

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80

        environment:

            - API_URL=http://localhost:8888

            #- API_URL=https://apis.identity.ariaos.online
